project_name: renderizer
builds:
  -
    binary: renderizer
    main: ./cmd/renderizer/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: '-s -w -X main.version={{.Version}} -X main.tag={{.Tag}} -X main.commitHash={{.FullCommit}} -X main.commitTime={{ index .Env "COMMIT_TIME" }} -X main.buildTime={{ time "20060102T150405" }}'

dist: build/dist

snapshot:
  name_template: '{{.Version}}.snapshot'

release:
  github:
    owner: gomatic
    name: renderizer

signs:
  -
    artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - docs
      - Merge pull request
      - Merge branch

archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  -
    # Name template of the recipe
    # Default to project name
    name: renderizer

    # GOARM to specify which 32-bit arm version to use if there are multiple versions
    # from the build section. Brew formulas support atm only one 32-bit version.
    # Default is 6 for all artifacts or each id if there a multiple versions.
    goarm: 6

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: gomatic
      name: homebrew-renderizer
      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    url_template: "https://github.com/metawave/renderizer/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: nicerobot@users.noreply.github.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/metawave/renderizer"

    # Your app's description.
    # Default is empty.
    description: "CLI to render Go template text files based on command line parameters and/or a YAML"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "GPL-3.0"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "renderizer"
