project_name: renderizer
builds:
  -
    binary: renderizer
    main: ./cmd/renderizer/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: '-s -w -X main.version={{.Version}} -X main.tag={{.Tag}} -X main.commit={{.Commit}} -X main.date={{ time "20060102" }}'

dist: release/dist

release:
  draft: true
